# Generated by Django 3.2 on 2021-04-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tx',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('txid', models.CharField(max_length=128)),
                ('from_addr', models.CharField(max_length=66)),
                ('to_addr', models.CharField(max_length=66)),
                ('value', models.CharField(max_length=128)),
                ('timestamp', models.BigIntegerField()),
                ('block_number', models.BigIntegerField()),
            ],
        ),
    ]
