# Generated by Django 3.2 on 2021-04-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.BigIntegerField()),
                ('txs', models.ManyToManyField(to='rest.Tx')),
            ],
        ),
    ]
