version: "3"

services:

  db:
    image: postgres:12.0
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: user
    ports:
      - 5432:5432
    networks:
      - main

  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    command: [
        "./compose/wait.sh", "db:5432",
        "--", "./compose/prestart.sh"
    ]
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://user:123@db/postgres
      APP_DEBUG: 0
      APP_PORT: 8080
      ALEMBIC_AUTOMIGRATE: 1
    volumes:
      - ./compose:/var/app/compose
    ports:
      - 8080:8080
    networks:
      - main
    depends_on:
      - db

networks:
  main:
